name: TPP-MLIR LLVM Build

on:
  workflow_dispatch:

env:
  NPROCS_LIMIT_LINK: 8

jobs:
  TPP-MLIR-LLVM-Base:
    runs-on: pcl-tiergarten
    steps:
      - uses: actions/checkout@v4
      - name: LLVM Base
        run: |-
              scripts/buildkite/check_llvm.sh || \
              ${{ secrets.SRUN }} --partition=spr-all --time=0:30:00 -- \
              'KIND=RelWithDebInfo COMPILER=clang \
              ${{ github.workspace }}/scripts/buildkite/build_llvm.sh'

  TPP-MLIR-LLVM-CUDA:
    runs-on: pcl-tiergarten
    steps:
      - uses: actions/checkout@v4
      - name: LLVM CUDA
        run: |-
              scripts/buildkite/check_llvm.sh || \
              ${{ secrets.SRUN }} --partition=a100,v100 --time=0:30:00 -- \
              'KIND=RelWithDebInfo COMPILER=clang GPU=cuda \
              ${{ github.workspace }}/scripts/buildkite/build_llvm.sh'

  TPP-MLIR-LLVM-Vulkan:
    runs-on: pcl-tiergarten
    steps:
      - uses: actions/checkout@v4
      - name: LLVM Vulkan
        run: |-
              scripts/buildkite/check_llvm.sh || \
              ${{ secrets.SRUN }} --partition=spr-all --time=0:30:00 -- \
              'KIND=RelWithDebInfo COMPILER=clang GPU=vulkan \
              ${{ github.workspace }}/scripts/buildkite/build_llvm.sh'

