name: TPP-MLIR Base Tests

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  NPROCS_LIMIT_LINK: 8
  SRUN: ${HOME}/srun.sh

jobs:
  Check_LLVM:
    uses: ./.github/workflows/tpp-llvm.yml
    secrets: inherit

  TPP-MLIR-gcc-rel:
    runs-on: pcl-tiergarten
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: GCC Release
        run: "${{ env.SRUN }} --partition=emr --time=0:30:00 -- \
            'KIND=Release COMPILER=gcc CHECK=1 ONEDNN=1 \
            ${{ github.workspace }}/scripts/buildkite/build_tpp.sh'"

  TPP-MLIR-gcc-deb:
    runs-on: pcl-tiergarten
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: GCC Debug
        run: "${{ env.SRUN }} --partition=emr --time=0:30:00 -- \
            'KIND=Debug COMPILER=gcc CHECK=1 ONEDNN=1 \
            ${{ github.workspace }}/scripts/buildkite/build_tpp.sh'"

  TPP-MLIR-clang-rel:
    runs-on: pcl-tiergarten
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: Clang Release
        run: "${{ env.SRUN }} --partition=emr --time=0:30:00 -- \
            'KIND=Release COMPILER=clang LINKER=lld CHECK=1 ONEDNN=1 \
            ${{ github.workspace }}/scripts/buildkite/build_tpp.sh'"

  TPP-MLIR-clang-deb:
    runs-on: pcl-tiergarten
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: Clang Debug Sanitizers
        run: "${{ env.SRUN }} --partition=emr --time=0:30:00 -- \
                'KIND=Debug COMPILER=clang LINKER=lld SANITIZERS=1 CHECK=1 ONEDNN=1 \
                ${{ github.workspace }}/scripts/buildkite/build_tpp.sh'"
