name: TPP-MLIR LLVM Build

on:
  workflow_dispatch:
  workflow_call:

env:
  NPROCS_LIMIT_LINK: 8
  SRUN: ${HOME}/srun.sh

jobs:
  TPP-MLIR-LLVM-Base:
    runs-on: pcl-tiergarten
    steps:
      - uses: actions/checkout@v4
      - name: LLVM Base
        run: |-
              scripts/buildkite/check_llvm.sh || \
              ${{ env.SRUN }} --partition=spr-all --time=0:30:00 -- \
              'KIND=RelWithDebInfo COMPILER=clang \
              ${{ github.workspace }}/scripts/buildkite/build_llvm.sh'

  TPP-MLIR-LLVM-CUDA:
    runs-on: pcl-tiergarten
    steps:
      - uses: actions/checkout@v4
      - name: LLVM CUDA
        run: |-
              GPU=cuda scripts/buildkite/check_llvm.sh || \
              ${{ env.SRUN }} --partition=a100,v100 --time=0:30:00 -- \
              'KIND=RelWithDebInfo COMPILER=clang GPU=cuda \
              ${{ github.workspace }}/scripts/buildkite/build_llvm.sh'
